name: Mirror GitHub to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync GitHub to GitLab
        uses: eskopp/github-to-gitlab@v2
        with:
          git_username: "ZXNrb3Bw"
          git_email: "aW5mb0BlcmlrLXNrb3BwLmRl"
          gitlab_repo: "aHR0cHM6Ly9naXRsYWIuZXJpay1za29wcC5kZS9naXRodWIvZGlhcnkuZ2l0"
          gitlab_token: ${{ secrets.GITLAB }}
          github_token: ${{ secrets.GITHUB }}
          base64: "true"
